version: '3'
services:
  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ../backend:/var/www/backend
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
      
  nginx:
    build:
      context: ./nginx
    volumes:
      - ../backend:/var/www/backend
      - ../frontend:/var/www/frontend
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "8080:8080"
    depends_on:
      - php-fpm

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: "sportshop"
      POSTGRES_PASSWORD: "sportshop"
      POSTGRES_DB: "sportshop"